name: Workflow Metrics
description: >
  Track and upload workflow execution time to CloudWatch

runs:
  using: composite
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::886436966712:role/Admin
        aws-region: us-west-2
    - name: Upload workflow metrics
      shell: bash
      run: |
        # Check if WORKFLOW_START_TIME is set
        if [ -z "$WORKFLOW_START_TIME" ]; then
        echo "Warning: WORKFLOW_START_TIME not set, skipping metrics upload"
        exit 0
        fi
        
        duration=$(($(date +%s) - $WORKFLOW_START_TIME))
        
        # Build job name with matrix values
        job_name="${{ github.job }}"
        if [ -z "${{ matrix.java-version }}" ]; then
        job_name="${job_name}(${{ matrix.java-version }})"
        fi
        if [ -z "${{ matrix.os }}" ]; then
        job_name="${job_name}(${{ matrix.os }})"
        fi
        
        aws cloudwatch put-metric-data \
          --namespace "GitHub/Workflows" \
          --metric-data '[{
            "MetricName": "Duration",
            "Value": '$duration',
            "Unit": "Seconds",
            "Dimensions": [
              {
                "Name": "WorkflowName",
                "Value": "${{ github.workflow }}"
              },
              {
                "Name": "JobName",
                "Value": "${{ github.job }}"
              },
              {
                "Name": "Repository", 
                "Value": "${{ github.repository }}"
              }
            ]
          }]'