/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0.
 */
package aws.sdk.kotlin.runtime.protocol.json

import software.aws.clientrt.client.ExecutionContext
import software.aws.clientrt.serde.*
import software.aws.clientrt.serde.xml.XmlSerialName

// Models "ErrorResponse" type in https://awslabs.github.io/smithy/1.0/spec/aws/aws-restxml-protocol.html#operation-error-serialization
internal data class XmlErrorResponse(
    val requestId: String?,
    val error: XmlError?,
    override val normalizedRequestId: String? = requestId ?: error?.requestId,
    override val normalizedErrorCode: String? = error?.code,
    override val normalizedErrorMessage: String? = error?.message
) : RestXmlErrorDetails

// Models "Error" type in https://awslabs.github.io/smithy/1.0/spec/aws/aws-restxml-protocol.html#operation-error-serialization
internal data class XmlError(
    val requestId: String?,
    val code: String?,
    val message: String?,
    val type: String?,
    override val normalizedRequestId: String? = requestId,
    override val normalizedErrorCode: String? = code,
    override val normalizedErrorMessage: String? = message
) : RestXmlErrorDetails

/**
 * Provides access to specific values regardless of message form
 */
interface RestXmlErrorDetails {
    val normalizedRequestId: String?
    val normalizedErrorCode: String?
    val normalizedErrorMessage: String?
}

// Returns parsed data in normalized form or throws IllegalArgumentException if unparsable.
internal suspend fun ExecutionContext.parseErrorResponse(payload: ByteArray): RestXmlErrorDetails {
    return ErrorResponseDeserializer.deserialize(deserializer(payload)) ?: XmlErrorDeserializer.deserialize(deserializer(payload)) ?: throw DeserializationException("Unable to deserialize error.")
}

/*
 * The deserializers in this file were initially generated by the SDK and then
 * adapted to fit this use case of deserializing well-known error structures from
 * restXml-based services.
 */

/**
 * Deserializes rest Xml protocol errors as specified by:
 * - Smithy spec: https://awslabs.github.io/smithy/1.0/spec/aws/aws-restxml-protocol.html#operation-error-serialization
 */
internal object ErrorResponseDeserializer {
    private val ERROR_DESCRIPTOR = SdkFieldDescriptor(SerialKind.Struct, XmlSerialName("Error"))
    private val REQUESTID_DESCRIPTOR = SdkFieldDescriptor(SerialKind.String, XmlSerialName("RequestId"))
    private val OBJ_DESCRIPTOR = SdkObjectDescriptor.build {
        trait(XmlSerialName("ErrorResponse"))
        field(ERROR_DESCRIPTOR)
        field(REQUESTID_DESCRIPTOR)
    }

    suspend fun deserialize(deserializer: Deserializer): XmlErrorResponse? {
        var requestId: String? = null
        var xmlError: XmlError? = null

        return try {
            deserializer.deserializeStruct(OBJ_DESCRIPTOR) {
                loop@ while (true) {
                    when (findNextFieldIndex()) {
                        ERROR_DESCRIPTOR.index -> xmlError = XmlErrorDeserializer.deserialize(deserializer)
                        REQUESTID_DESCRIPTOR.index -> requestId = deserializeString()
                        null -> break@loop
                        else -> skipValue()
                    }
                }
            }

            XmlErrorResponse(requestId, xmlError)
        } catch (e: DeserializerStateException) {
            null // return so an appropriate exception type can be instantiated above here.
        }
    }
}

/**
 * This deserializer is used for both the nested Error node from ErrorResponse as well as the top-level
 * Error node as described in https://awslabs.github.io/smithy/1.0/spec/aws/aws-restxml-protocol.html#operation-error-serialization
 */
internal object XmlErrorDeserializer {
    private val MESSAGE_DESCRIPTOR = SdkFieldDescriptor(SerialKind.String, XmlSerialName("Message"))
    private val CODE_DESCRIPTOR = SdkFieldDescriptor(SerialKind.String, XmlSerialName("Code"))
    private val TYPE_DESCRIPTOR = SdkFieldDescriptor(SerialKind.String, XmlSerialName("Type"))
    private val REQUESTID_DESCRIPTOR = SdkFieldDescriptor(SerialKind.String, XmlSerialName("RequestId"))
    private val OBJ_DESCRIPTOR = SdkObjectDescriptor.build {
        trait(XmlSerialName("Error"))
        field(MESSAGE_DESCRIPTOR)
        field(CODE_DESCRIPTOR)
        field(TYPE_DESCRIPTOR)
        field(REQUESTID_DESCRIPTOR)
    }

    suspend fun deserialize(deserializer: Deserializer): XmlError? {
        var message: String? = null
        var code: String? = null
        var type: String? = null
        var requestId: String? = null

        return try {
            deserializer.deserializeStruct(OBJ_DESCRIPTOR) {
                loop@ while (true) {
                    when (findNextFieldIndex()) {
                        MESSAGE_DESCRIPTOR.index -> message = deserializeString()
                        CODE_DESCRIPTOR.index -> code = deserializeString()
                        TYPE_DESCRIPTOR.index -> type = deserializeString()
                        REQUESTID_DESCRIPTOR.index -> requestId = deserializeString()
                        null -> break@loop
                        else -> skipValue()
                    }
                }
            }

            XmlError(requestId, code, message, type)
        } catch (e: DeserializerStateException) {
            null // return so an appropriate exception type can be instantiated above here.
        }
    }
}
