/*
 * Generated by AWS SDK for Kotlin Custom SDK Build Plugin
 * DO NOT EDIT - This file is automatically generated
 */
package aws.sdk.kotlin.gradle.customsdk

/**
 * Configuration class for DynamoDB service operations.
 * Provides type-safe selection of operations for custom SDK generation.
 */
class DynamoDbServiceConfiguration : ServiceConfiguration() {
    
    /**
     * Select specific operations to include in the custom SDK.
     * 
     * @param operations The operations to include, using typed constants from DynamoDbOperation
     */
    fun operations(vararg operations: DynamoDbOperation) {
        selectedOperations.addAll(operations.map { OperationConstant(it.shapeId) })
    }
    
    /**
     * Select operations to include in the custom SDK.
     * 
     * @param operations The operations to include, using typed constants from DynamoDbOperation
     */
    fun operations(operations: List<DynamoDbOperation>) {
        selectedOperations.addAll(operations.map { OperationConstant(it.shapeId) })
    }
}
