/*
 * Generated by AWS SDK for Kotlin Custom SDK Build Plugin
 * DO NOT EDIT - This file is automatically generated
 */
package aws.sdk.kotlin.gradle.customsdk

/**
 * Typed operation constants for DynamoDB service.
 * These constants provide type-safe operation selection and IDE autocompletion.
 */
enum class DynamoDbOperation(val shapeId: String) {
    /**
     * Returns a set of attributes for the item with the given primary key
     */
    GetItem("com.amazonaws.dynamodb#GetItem"),
    
    /**
     * Creates a new item, or replaces an old item with a new item
     */
    PutItem("com.amazonaws.dynamodb#PutItem"),
    
    /**
     * Deletes a single item in a table by primary key
     */
    DeleteItem("com.amazonaws.dynamodb#DeleteItem"),
    
    /**
     * Edits an existing item's attributes, or adds a new item to the table
     */
    UpdateItem("com.amazonaws.dynamodb#UpdateItem"),
    
    /**
     * Finds items based on primary key values
     */
    Query("com.amazonaws.dynamodb#Query"),
    
    /**
     * Returns one or more items and item attributes
     */
    Scan("com.amazonaws.dynamodb#Scan")
}
