/*
 * Generated by AWS SDK for Kotlin Custom SDK Build Plugin
 * DO NOT EDIT - This file is automatically generated
 */
package aws.sdk.kotlin.gradle.customsdk

/**
 * Typed operation constants for Lambda service.
 * These constants provide type-safe operation selection and IDE autocompletion.
 */
enum class LambdaOperation(val shapeId: String) {
    /**
     * Invokes a Lambda function
     */
    Invoke("com.amazonaws.lambda#Invoke"),
    
    /**
     * Creates a Lambda function
     */
    CreateFunction("com.amazonaws.lambda#CreateFunction"),
    
    /**
     * Deletes a Lambda function
     */
    DeleteFunction("com.amazonaws.lambda#DeleteFunction"),
    
    /**
     * Updates a Lambda function's code
     */
    UpdateFunctionCode("com.amazonaws.lambda#UpdateFunctionCode"),
    
    /**
     * Returns a list of Lambda functions
     */
    ListFunctions("com.amazonaws.lambda#ListFunctions"),
    
    /**
     * Returns information about the function
     */
    GetFunction("com.amazonaws.lambda#GetFunction")
}
