/*
 * Generated by AWS SDK for Kotlin Custom SDK Build Plugin
 * DO NOT EDIT - This file is automatically generated
 */
package aws.sdk.kotlin.gradle.customsdk

/**
 * Typed operation constants for S3 service.
 * These constants provide type-safe operation selection and IDE autocompletion.
 */
enum class S3Operation(val shapeId: String) {
    /**
     * Retrieves objects from Amazon S3
     */
    GetObject("com.amazonaws.s3#GetObject"),
    
    /**
     * Adds an object to a bucket
     */
    PutObject("com.amazonaws.s3#PutObject"),
    
    /**
     * Removes an object from a bucket
     */
    DeleteObject("com.amazonaws.s3#DeleteObject"),
    
    /**
     * Returns some or all objects in a bucket
     */
    ListObjects("com.amazonaws.s3#ListObjects"),
    
    /**
     * Creates a new S3 bucket
     */
    CreateBucket("com.amazonaws.s3#CreateBucket"),
    
    /**
     * Deletes an S3 bucket
     */
    DeleteBucket("com.amazonaws.s3#DeleteBucket")
}
