/*
 * Generated by AWS SDK for Kotlin Custom SDK Build Plugin
 * DO NOT EDIT - This file is automatically generated
 */
package aws.sdk.kotlin.gradle.customsdk

/**
 * Configuration class for S3 service operations.
 * Provides type-safe selection of operations for custom SDK generation.
 */
class S3ServiceConfiguration : ServiceConfiguration() {
    
    /**
     * Select specific operations to include in the custom SDK.
     * 
     * @param operations The operations to include, using typed constants from S3Operation
     */
    fun operations(vararg operations: S3Operation) {
        selectedOperations.addAll(operations.map { OperationConstant(it.shapeId) })
    }
    
    /**
     * Select operations to include in the custom SDK.
     * 
     * @param operations The operations to include, using typed constants from S3Operation
     */
    fun operations(operations: List<S3Operation>) {
        selectedOperations.addAll(operations.map { OperationConstant(it.shapeId) })
    }
}
